const app=document.querySelector('#app'), topbar=document.querySelector('#topbar'), progress=document.querySelector('#progress'), chapterLabel=document.querySelector('#chapterLabel');
const S={step:Number(localStorage.getItem('us-step')||0), cheek:false};
const photos=Array.from({length:15},(_,i)=>`assets/photos/memory-${String(i+1).padStart(2,'0')}.jpg`);
const save=n=>{S.step=n;localStorage.setItem('us-step',n)};
const toast=t=>{const x=document.querySelector('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1700)};
const vib=()=>navigator.vibrate?.(25);
function hearts(){setInterval(()=>{const h=document.createElement('span');h.className='heart';h.textContent=Math.random()>.45?'♡':'♥';h.style.left=Math.random()*100+'vw';h.style.fontSize=12+Math.random()*22+'px';h.style.animationDuration=6+Math.random()*6+'s';document.querySelector('#hearts').append(h);setTimeout(()=>h.remove(),12000)},900)}hearts();
function setTop(i,label){topbar.classList.toggle('hidden',i===0);progress.style.width=`${Math.max(0,(i-1)/(steps.length-2))*100}%`;chapterLabel.textContent=label||'Our Story'}
function render(html,i,label){setTop(i,label);app.innerHTML=`<section class="screen">${html}</section>`;window.scrollTo(0,0)}
function next(){go(Math.min(S.step+1,steps.length-1))} function go(i){save(i);steps[i]();}
function question({chapter,title,text,choices,correct,after}){render(`<div class="card"><div class="chapterNo">${chapter}</div><h2>${title}</h2><p class="story">${text}</p><div class="choices">${choices.map((c,i)=>`<button class="choice" data-i="${i}">${c}</button>`).join('')}</div></div>`,S.step,chapter);document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{if(+b.dataset.i===correct){b.classList.add('correct');vib();toast('I knew you’d remember ❤️');setTimeout(()=>after?after():next(),650)}else{b.classList.add('wrong');toast(['Baby 😭 try again','Womp womp womp 😭','Absolutely not 😂 try again'][Math.floor(Math.random()*3)]);setTimeout(()=>b.classList.remove('wrong'),500)}})}
const steps=[
()=>render(`<div class="hero"><div class="eyebrow">A 2½ month anniversary experience</div><h1>For <em>Hope</em> ❤️</h1><img class="heroPhoto" src="${photos[7]}" alt="A memory of us"><p class="sub">Baby, I made you a little something. Not just a website — our story, turned into a tiny world for you to unlock.</p><button class="primary" onclick="next()">Begin our story →</button><p class="tiny">Made by your bubs, with a ridiculous amount of love.</p></div>`,0,'For Hope'),
()=>{render(`<div class="card"><div class="chapterNo">Chapter One · Before Us</div><h2>It started with one follow.</h2><p class="story">Before the dates, the drives, the sushi and all the memories… there was Instagram.</p><div class="dm"><div class="bubble me">😍</div><div class="bubble her">Thank you</div></div><p class="tiny">A flawless opening line, obviously.</p><button class="primary" onclick="next()">Okay, keep going</button></div>`,1,'Before Us')},
()=>question({chapter:'Memory Check · 01',title:'Who made the first move?',text:'Be careful. The story cannot continue until history is respected 😂',choices:['Hope followed & messaged first','Adam followed & messaged first','We both somehow did it at once'],correct:1}),
()=>question({chapter:'Memory Check · 02',title:'The legendary first message…',text:'What did I send you?',choices:['“Hey”','❤️','😍','A whole paragraph'],correct:2}),
()=>{render(`<div class="card"><div class="chapterNo">Chapter Two · The Party</div><h2>Then I met you for real.</h2><p class="story">And my first thought? You were <strong>drop-dead gorgeous</strong>. Then we started talking and somehow it felt easy immediately. You were fun. We just… hit it off.</p><img class="memoryImg" src="${photos[12]}" alt="Us together"><button class="primary" onclick="next()">Unlock the first kiss →</button></div>`,4,'The Party')},
()=>{render(`<div class="card"><div class="chapterNo">Interactive Memory</div><h2>Where did I point first?</h2><p class="story">Tap the right place in the right order.</p><div class="tapFace"><button id="cheek">CHEEK ♡</button><button id="mouth">MOUTH ♡</button></div><p id="kissText" class="story tiny">One tap started something pretty important…</p></div>`,5,'First Kiss');document.querySelector('#cheek').onclick=()=>{S.cheek=true;vib();document.querySelector('#kissText').textContent='You kissed my cheek… then I got brave 😭';toast('Correct ❤️ now what happened next?')};document.querySelector('#mouth').onclick=()=>{if(!S.cheek)return toast('Not yet, baby 😂');vib();document.querySelector('#kissText').textContent='…I pointed at my mouth, and you kissed me. ❤️';setTimeout(next,1300)}},
()=>{render(`<div class="card"><div class="chapterNo">Chapter Three · 22.03.2024</div><h2>Our first proper date.</h2><p class="story">The Waterfront. Breakfast first. Then the docks. A normal day that quietly became one of the most important dates in my life.</p><img class="memoryImg" src="${photos[0]}" alt="Us by the beach"><button class="primary" onclick="next()">Test my girlfriend →</button></div>`,6,'22.03.2024')},
()=>question({chapter:'Waterfront Check · 01',title:'Breakfast was where?',text:'This one should be easy 👀',choices:['Wimpy','Spur','Mugg & Bean','We skipped breakfast'],correct:1}),
()=>question({chapter:'Waterfront Check · 02',title:'And what did we order?',text:'The extremely important historical detail.',choices:['Two Unreal Breakfasts','Two burgers','Pancakes','Sushi, obviously'],correct:0}),
()=>{render(`<div class="card"><div class="chapterNo">The Docks · 22 March 2024</div><h2>Then came the photo.</h2><p class="story">An Instax. One little picture. And one sentence that changed what we were.</p><div class="polaroid"><div class="blank">The real photo is still with you. ♡</div><p>22.03.2024</p></div><button class="primary" onclick="next()">Develop the memory</button></div>`,9,'The Docks')},
()=>question({chapter:'The Question',title:'What did I say?',text:'At the docks, after taking your photo…',choices:['“You look cute.”','“This is a photo of my girlfriend.”','“Keep this forever.”','“Should we go home?”'],correct:1}),
()=>{render(`<div class="card" style="text-align:center"><div class="chapterNo">And you said…</div><div class="quote">“Yes, I will be.”</div><p class="story">And just like that, there was an <strong>us</strong>. ❤️</p><div class="endDate">22.03.2024</div><button class="primary" onclick="next()">Continue our story</button></div>`,11,'Officially Us')},
()=>{render(`<div class="card"><div class="chapterNo">Chapter Four · Our Little Things</div><h2>My favourite kind of plans.</h2><div class="road"><div class="moon"></div><div class="car">🚗</div></div><p class="story">Drives to the beach. The Strip. Sitting and talking with nowhere else we need to be. Sometimes sushi. Sometimes just us.</p><button class="primary" onclick="next()">Road trip memory →</button></div>`,12,'Our Little Things')},
()=>question({chapter:'Drive Check',title:'Where do our drives usually lead?',text:'No GPS needed for this one.',choices:['The mall','The Strip / beach','The mountains','Straight back home'],correct:1}),
()=>question({chapter:'Sushi Check 🍣',title:'What’s your order?',text:'I better know this. And so should you 😂',choices:['8 salmon roses','4 rice rolls + 4 crumbed','A 12-piece California roll','No sushi'],correct:1}),
()=>{render(`<div class="card"><div class="chapterNo">The Things I Notice</div><h2>You make love feel easy.</h2><p class="story">The random hugs. The kisses when I’m not expecting them. How kind you are. How attentive you are. And yes… your cute cheeks. Especially those cheeks. ❤️</p><img class="memoryImg" src="${photos[6]}" alt="A Christmas kiss"><button class="primary" onclick="next()">A few of my favourite memories</button></div>`,15,'Why You')},
()=>{render(`<div style="width:min(100%,760px)"><div class="eyebrow">Unlocked · Our Camera Roll</div><h2 style="font-family:Georgia,serif;font-size:40px;margin-top:0">Little pieces of us.</h2><div class="gallery"><img src="${photos[5]}"><img src="${photos[7]}"><img src="${photos[10]}"><img class="wide" src="${photos[0]}"><img src="${photos[1]}"><img src="${photos[4]}"></div><br><button class="primary" onclick="next()">There’s more →</button></div>`,16,'Memories')},
()=>{render(`<div style="width:min(100%,760px)"><div class="eyebrow">Moving memories</div><h2 style="font-family:Georgia,serif;font-size:40px;margin-top:0">Press play, baby.</h2><div class="gallery"><video controls playsinline preload="metadata" src="assets/videos/memory-1.mp4"></video><video controls playsinline preload="metadata" src="assets/videos/memory-3.mp4"></video><video class="wide" controls playsinline preload="metadata" src="assets/videos/memory-2.mp4"></video></div><br><button class="primary" onclick="next()">Keep going ❤️</button></div>`,17,'Memories')},
()=>{render(`<div class="card"><div class="chapterNo">Secret achievement unlocked</div><h2>Womp womp womp.</h2><p class="story">No context. No explanation. If you know, you know. 😭</p><button class="primary" onclick="next()">😭 continue</button></div>`,18,'Inside Jokes')},
()=>{render(`<div class="card"><div class="chapterNo">Our soundtrack</div><h2>“My Favorite Part”</h2><p class="story">Mac Miller & Ariana Grande. I’m not putting the song itself in here — because somehow the memory of it already sounds like us.</p><button class="primary" onclick="next()">Now look forward →</button></div>`,19,'Our Song')},
()=>{render(`<div class="card"><div class="chapterNo">Chapter Five · What Comes Next</div><h2>We’ve made memories. Now imagine the ones we haven’t made yet.</h2><div class="futureGrid"><div class="future"><b>🏡</b>Our modern home</div><div class="future"><b>👨‍👩‍👧‍👦</b>Our kids</div><div class="future"><b>🇮🇹</b>Venice, Italy</div><div class="future"><b>✝️</b>Love & faith</div></div><button class="primary" onclick="next()">One last chapter</button></div>`,20,'Our Future')},
()=>{render(`<div class="card" style="text-align:center"><div class="chapterNo">For Hope Amy Adonis</div><h2>Why I choose you.</h2><p class="finalLetter">Baby, I choose you because I believe we are <strong>two halves coming together as one</strong>. We make a great team. I want us to keep driving through life together with our love and our faith in the Lord guiding us.<br><br>In only two and a half months, we’ve already made moments I never want to forget. And somehow, what excites me most isn’t only everything behind us — it’s everything still ahead.</p><button class="primary" onclick="next()">Finish the experience</button></div>`,21,'For You')},
()=>{render(`<div style="text-align:center;max-width:600px"><div class="eyebrow">The End.</div><h1 class="bigTitle">…well,<br>the end of <em style="color:var(--rose);font-weight:400">this part.</em></h1><p class="finalLetter" style="margin:25px auto">This game had to end somewhere. <strong>Our story doesn’t.</strong><br><br>There are places we haven’t been, memories we haven’t made, a home we haven’t built and a whole life we haven’t lived.<br><br>So baby, the experience ends here — but I hope this is only the beginning of a very, very long life together.</p><div class="endDate">22.03.2024 → ∞</div><button class="softBtn" onclick="next()">To be continued… ∞</button></div>`,22,'The Beginning')},
()=>{render(`<div class="hero"><div class="eyebrow">2½ months down · forever to go</div><img class="heroPhoto" src="${photos[7]}" alt="Us"><h1>I love <em>us.</em> ❤️</h1><p class="sub">Happy two-and-a-half-month anniversary, baby.</p><button class="softBtn" id="restart">Replay our story</button></div>`,23,'Us ❤️');document.querySelector('#restart').onclick=()=>{if(confirm('Replay from the beginning?'))go(0)}}
];
document.querySelector('#homeBtn').onclick=()=>{if(confirm('Go back to the beginning? Your progress will reset.'))go(0)};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
go(Math.min(S.step,steps.length-1));
